### ISSUE TITLE
Erc20Vault and ETHVault are deployed by maintainer 

### ISSUE THREAD

**Issue by thec00n** [omgnetwork/plasma-contracts#578]
## Issue Type 

```
[ x ] bug report
[ ] feature request
```

## Current Behavior

It is unnecessary to deploy a ERC20Vault and ETHVault from the maintainer address. All contracts should be deployed by the deployer. 

https://github.com/omisego/plasma-contracts/blob/a36f318195d30fc676222adacc2b93da270c8694/plasma_framework/migrations/3_deploy_and_register_eth_vault.js#L22-L27

https://github.com/omisego/plasma-contracts/blob/a36f318195d30fc676222adacc2b93da270c8694/plasma_framework/migrations/4_deploy_and_register_erc20_vault.js#L22

## Expected Behavior
Deploying contracts from the maintainer address might add additional effort when deploying production environments.

**Comment by InoMurko** [comment]
I'll take this one. Hopefully Ill figure out what needs to be done.

**Comment by achiurizo** [comment]
Closing this as this was resolved cc @InoMurko
