### ISSUE TITLE
Increase test coverage for exit priority 

### ISSUE THREAD

**Issue by thec00n** [omgnetwork/plasma-contracts#605]
## Issue Type 

```
[x ] bug report
[ ] feature request
```

## Current Behavior
Three values are wrapped up into the exit priority. Based on the documentation the following assumptions are made on now long the scheme can be used for the exitable timestamp as well as the block numbers.

```
    *   42 bits  - timestamp in seconds (exitable_at); we can represent dates until year 141431
    *   54 bits  - blknum * CHILD_BLOCK_INTERVAL * 10^5 + txindex; 54 bits represent all transactions for 85 years. 
        We are assuming CHILD_BLOCK_INTERVAL = 1000.
    *   160 bits - exit id
```

I could not find a test that confirms the values indicated above.

## Expected Behavior
Implement tests that confirm that the exitable timestamp and the blocknumber can be used for the time durations indicated. Additionally confirm with the tests that neither exitable timestamp or the blocknumber overflow or overwrite the other values packed into exit priority once the value reaches the upper bounds of its limits.

**Comment by kevsul** [comment]
Closed by https://github.com/omgnetwork/plasma-contracts/pull/631
