### ISSUE TITLE
fix flaky python test

### ISSUE THREAD

**Issue by boolafish** [omgnetwork/plasma-contracts#606]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior
There is one python test that is quite flaky: `test_should_not_allow_to_withdraw_inputs_and_outputs_when_ifes_processing_interchanges `

https://app.circleci.com/pipelines/github/omisego/plasma-contracts/1977/workflows/2cf05327-796a-4bcc-9ee9-3723107f0741/jobs/10277

In some previous PR, we have experienced that some unrelated change causing the test to fail. 

And see the slack discussion: [here](https://omgnetworkhq.slack.com/archives/C9KNA675J/p1583338638344000)

## Expected Behavior
Be stable

## Suggested Fix

My current guess is that the priority does not strictly follow our first come first server order as the timestamp in blockchain is not really that reliable when two tx comes consecutively.

As a result, the order of priority queue might be a bit unexpected.

**Comment by InoMurko** [comment]
https://app.circleci.com/pipelines/github/omgnetwork/plasma-contracts/2323/workflows/ee053da0-4923-4dc9-a431-68a01bdd2205/jobs/12198
Started re-appearing.

**Comment by boolafish** [comment]
sigh, anyone has idea what can we try? @kevsul @pgebal @thec00n

**Comment by boolafish** [comment]
rechecked why previous attempt failed. During piggyback, it will enqueue with exit-able timestamp base on the following formula:

`return uint32(Math.max(_blockTimestamp + (_calculator.minExitPeriod * 2), _now + _calculator.minExitPeriod));`

So the problem is that it is using the `_blockTimestamp + (_calculator.minExitPeriod * 2)` part instead of `_now + _calculator.minExitPeriod` as the `minExitPeriod` (4min in python test setup) is longer than what I time travelled the ganache. Basically, the two competing txs are and should be of same priority 🤷‍♂️.

In fact, the test setup does not makes much sense as they are two competing txs with one suppose to be canonical (as included in a block) and the other non-canonical. However, no challenge was involved in the test. I will scan through all tests in `test_process_exits.py` and come up with a proposal to update/remove/change this test or not.
