### ISSUE TITLE
[fast exits] Ensure token wrapping SE can be redeemed

### ISSUE THREAD

**Issue by pik694** [omgnetwork/plasma-contracts#628]
## Issue Type 
```
[ ] bug report
[x] feature request
```
## Overview
The scope of the task is to ensure that once a wrapped SE is processed, the token can be redeemed and funds are sent to the token owner.

### Possible issues
1. Ensure challenged exit is burnt and NFT owner does not receive any funds. The discussion started here: https://github.com/omisego/plasma-contracts/pull/625#discussion_r425590972.

### Blockers
Blocked by #626

**Comment by pik694** [comment]
ad. possible blocker 1 - Could anyone challenge an exit started by LC? It is not an owned account, therefore double-spend is not possible. 

cc: @boolafish

**Comment by boolafish** [comment]
Seems like not possible in Payment tx.

Btw, might worth to check whether we can rely on the `isOutputFinalized(outputId)` instead or not to check the finalization of the exit/output?

https://github.com/omisego/plasma-contracts/blob/7afc0b62623bc3f34e612256c3e2fd9a3e531a2c/plasma_framework/contracts/src/framework/ExitGameController.sol#L230

**Comment by pik694** [comment]
The usual scenario of Alice <-> LC interaction is as follows: 
  Alice spends `utxo1` in `tx1` sending it to LC and creating `utxo2`, Alice starts SE on `utxo2` via LC.

  In order to simplify the protocol and therefore to make it more secure, we only allow `tx1` to have exactly one input and one output.

## Tx1 mined in an invalid block
If a transaction is mined in an invalid block, but the transaction is itself canonical, Plasma provides in-flight exits mechanisms, which could be also used in this case:
Alice starts IFE on `tx1`, Alice piggybacks `utox2` via LC. 

NOTE: LC must proxy piggybacking.

## Attacks on Standard Exit
When starting a SE on `utxo2`, Alice must be sure that `tx1` has been mined in a valid block. All other attacks are neglected, from LC perspective, as they are taken care by Plasma protocol.

### Double spend on `utxo2`
Since `utxo2` is not owned by a user owned account, `utxo2` cannot be spent in any other way than by starting an exit (everywhere else the spender must fulfill spending condition). 
In case of `payment` output type only accounts with private keys can fulfill spending condition. 
As we make here assumption on output type, we should probably in this case __restrict the LC to work with just certain output types__, so that we are certain that LC funds are safe.

### IFE started on `tx1`
One attack might be to start an IFE on `tx1` with higher priority than priority of SE on `utxo2`, but since the tx1 canonicity assumption is made, no one can challenge tx1. 
On the other hand, since Alice can both start a SE and IFE (and piggyback it), the LC must create at most one NFT per output - Plasma Framework distinguishes outputs using output id,
   so should LC.

### IFE on tx spending `utxo2`
Non-viable as `utxo2` is of a certain type, and there cannot exist a valid tx that spends `utxo2`.

### Other variations of IFEs
There also exit many other variations of IFEs that can be started and that may have `utox1` in common, but in this case it is usually not possible to
be certain about the final state of a piggybacked output, unless having full information.
Having this said, Liquidity Contract tokens are recommended to be bought only by the parties that are have full knowledge and are sure about the final state of the certain output.
