### ISSUE TITLE
[fast exits] Pay back exit bond

### ISSUE THREAD

**Issue by pik694** [omgnetwork/plasma-contracts#629]
## Issue Type 
```
[ ] bug report
[x] feature request
```
## Overview 
The scope of the task is to provide a mechanism that would ensure, that the exit bond is paid back. 

### Open questions
1. Should bond be returned to the party that started the exit or to the party that last owned the NFT?

### Blockers
Blocked by #626

**Comment by pik694** [comment]
@whoisjeremylam can you help us with the question 1.?

**Comment by whoisjeremylam** [comment]
From what I understand, the bond is to incentivise a user to process exits in the queue. Given that the party that started the exit no longer has an interest in the exit, I think the bond should go to the party that owns the NFT.

**Comment by boolafish** [comment]
>  the bond is to incentivise a user to process exits in the queue

Hmmm.....I think it is more to incentivize people to challenge the exit. It makes sure that the action of challenge should not cost the user doing the challenge. (and ideally some reward) Given this, probably it makes more sense to return to the exit initiator?

But probably it does help incentives process exit too which is sth I was not aware of actually 🤔

**Comment by kevsul** [comment]
Yeah, I believe the primary objective of the bond is to cover the cost of challenging.
But it also plays a part of dis-incentivising users from starting invalid challenges.

In the case of a normal exit, the bond is an upfront cost that the user expects to get back as long as their exit is valid.
I think it should be the same for fast exit - the bond is put up by exit initiator and they should get it back if the exit was valid.

**Comment by whoisjeremylam** [comment]
Phew thanks for correcting me! Please listen to these guys ☝️

**Comment by pik694** [comment]
yeah, I have always been thinking about bond mechanism just what @kevsul wrote.

@whoisjeremylam does this change your answer? should we be sending the bond to NFT owner?

**Comment by whoisjeremylam** [comment]
I agree with @kevsul. We need to preserve the dis-incentive to start invalid exits. Let's pay back the exit bond to the exit initiator.

This is becoming quite complex though for the exit initiator. Even though they have 'fast exited' I assume they need to come back later to claim the bond? What is the process to do this?

We may need to look at this process again when we have user input.
