### ISSUE TITLE
Emit IFE finalized event in V2.0

### ISSUE THREAD

**Issue by boolafish** [omgnetwork/plasma-contracts#646]
## Issue Type 
```
[ ] bug report
[x] feature request
```

## Current Behavior
IFE would only emit event when it is piggybacked.

## Expected Behavior
There should be event showing the iFE itself is finalized no matter piggybacked or not.

## Suggested Fix
add one line to emit the event

## Motivation for Change
 let the downstream service happier and easier to see what has happened on chain.
also: https://github.com/omgnetwork/security-issues/issues/32

**Comment by pgebal** [comment]
I'm taking this task, it's a part of solving the issue that @boolafish mentioned.
