### ISSUE TITLE
python test failure

### ISSUE THREAD

**Issue by boolafish** [omgnetwork/plasma-contracts#664]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Note
test is failing with message `VM Exception while processing transaction: stack underflow`

https://app.circleci.com/pipelines/github/omgnetwork/plasma-contracts/2354/workflows/7489954e-7f6b-4909-809c-a279b8bf2b77/jobs/12396

Might be related to https://github.com/trufflesuite/ganache-cli/issues/465

**Comment by boolafish** [comment]
okay.....seems like actually all the python tests are failing now 🤦‍♂️ probably we should prioritize this one

**Comment by InoMurko** [comment]
done
