### ISSUE TITLE
testing of two steps to exit game

### ISSUE THREAD

**Issue by InoMurko** [omgnetwork/plasma-contracts#671]
Context: https://omgnetworkhq.slack.com/archives/C7V603752/p1596177780442900?thread_ts=1596126516.425200&cid=C7V603752
PR: https://github.com/omgnetwork/plasma-contracts/pull/667

@boolafish so I renamed the router functions from init  to boot  and changed their visibility from public  to internal
https://github.com/omgnetwork/plasma-contracts/pull/667/commits/174cee073410c39a448416f676deaf6d228d6281#r463966820

this brings a whole range of changes because if you want to test these Routers, you need to always deploy and initialize PaymentExitGame. And PaymentExitGame does not deploy the Mock contracts so these tests wouldn’t work.

So what is the normal approach to do this in Solidity? Is to create a `PaymentExitGameMock` that deploys Router Mocks?

**Comment by boolafish** [comment]
> this brings a whole range of changes because if you want to test these Routers, you need to always deploy and initialize PaymentExitGame. And PaymentExitGame does not deploy the Mock contracts so these tests wouldn’t work.

I don't quite get this actually. We already have `PaymentInFlightExitRouterMock` and `PaymentStandardExitRouterMock`, to test the internal function (`boot(args)` in your commit), those mocks seems to be enough?

Not sure what you mean `you need to always and initialize PaymentExitGame. And PaymentExitGame does not deploy the Mock contracts...`

**Comment by InoMurko** [comment]
I can't call `PaymentInFlightExitRouterMock.boot/1` from tests since they're internal, right?

**Comment by boolafish** [comment]
Oh that is the purpose of those mocks. It proxy the call to the internal function via a public function to allow easier testing

**Comment by InoMurko** [comment]
ahaaaaa, okay, so the two mocks needs to implement:
```
function boot_internal(PaymentExitGameArgs.Args memory args)
        public
{
        PaymentStandardExitRouter.boot(args);
        framework = args.framework;
    }
```
and I'm good!
