### ISSUE TITLE
Please add mainnet address to readme

### ISSUE THREAD

**Issue by chriseth** [omgnetwork/plasma-contracts#675]
After several minutes of digging on https://omg.network/ and in this repository, I was not able to find the actual addresses of the deployed contracts on mainnet. I think it would increase trust if you put the addresse(s) in the readme of the repository. If people want to browse the source code before using this product, the content on github is mostly irrelevant, it only matters what is on chain. In connection to this, it would also be nice if you could add the source to https://sourcify.dev/ if you have not done that yet.

Thanks a lot!

**Comment by jbunce** [comment]
Hi @chriseth. Have you seen our documentation? It's defined here https://docs.omg.network/environments. Hope this helps.

**Comment by jbunce** [comment]
As for the contract source code, we've verified it on Etherscan at https://etherscan.io/address/0x0d4c1222f5e839a911e2053860e45f18921d72ac#code

**Comment by chriseth** [comment]
Ah nice! Yes, that's what I was looking for, so it's probably enough.

If I may hijack this issue for something related: Do you still have the metadata file produced at deploy time so that the source code can be fully verified, or at least is the compilation process reproducibly documented?

**Comment by jbunce** [comment]
We don't have the metadata file.

We deployed the mainnet contracts with SHA `a69c763f239b81c5eb46b0bbdef3459f764360dc `, which is the release `v1.0.4` https://github.com/omgnetwork/plasma-contracts/releases/tag/v1.0.4

The compile and deployment process is identical to the README in the root of the repo so you will be able to replicate this process.

**Comment by chriseth** [comment]
Ok, then I'll just try that, thanks!
