### ISSUE TITLE
Properly set v2.0 branch as base or master branch

### ISSUE THREAD

**Issue by boolafish** [omgnetwork/plasma-contracts#691]
## Issue Type 

```
[ ] bug report
[x] feature request
```

## Current Behavior
We have swap the base branch, but not all previously set CI stuff and tests are running on the new base branching.

## Expected Behavior
At least make v2.0.0 branch has all the tests and check if there is anything missing

**Comment by souradeep-das** [comment]
Enabled python long-running tests, github actions and deployment to rinkeby works after sequential deployments.
